//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SzarFramework.Querys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SzarFramework.Querys.sql", typeof(sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TableID
        ///      , FieldID
        ///      , AliasID
        ///      , Descr
        ///      , TypeID
        ///      , EditType
        ///      , SizeID
        ///      , EditSize
        ///      , Dflt
        ///      , NotNull
        ///      , IndexID
        ///      , RTable
        ///      , RField
        ///      , Action
        ///      , Sys
        ///      , DfltDate
        ///      , RelUDO
        ///  FROM CUFD.
        /// </summary>
        internal static string cufdList {
            get {
                return ResourceManager.GetString("cufdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fieldid from CUFD where AliasID = &apos;{0}&apos; and TableID = &apos;{1}&apos;.
        /// </summary>
        internal static string getFieldID {
            get {
                return ResourceManager.GetString("getFieldID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///       TableName
        ///       ,Descr
        ///       ,TblNum
        ///       ,ObjectType
        ///       ,UsedInObj
        ///       ,LogTable
        ///       ,Archivable
        ///       ,ArchivDate 
        ///from OUTB.
        /// </summary>
        internal static string outbList {
            get {
                return ResourceManager.GetString("outbList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Code, NewFormSrf from OUDO where Code = &apos;{0}&apos;.
        /// </summary>
        internal static string udoList {
            get {
                return ResourceManager.GetString("udoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [TableID]
        ///      ,[FieldID]
        ///      ,[IndexID]
        ///      ,[FldValue]
        ///      ,[Descr]
        ///      ,[FldDate]
        ///  FROM [UFD1] 
        ///  where tableid = &apos;{0}&apos; 
        ///        and fieldid = (select FieldID from CUFD where TableID = &apos;{0}&apos; and AliasID = &apos;{1}&apos;).
        /// </summary>
        internal static string ufd1List {
            get {
                return ResourceManager.GetString("ufd1List", resourceCulture);
            }
        }
    }
}
